name: Build Unity IPA

on:
  workflow_dispatch:

jobs:
  build-ipa:
    runs-on: macos-latest
    
    steps:
      - name: Download Xcode project zip
        run: curl -L -o xcode_project.zip "https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBdUdxSWRaOEpvV2NpY29UNGZ2WDBXbG1HdW1rdEE_ZT12dzFpaTc/root/content"
      
      - name: Extract Xcode project
        run: unzip xcode_project.zip
      
      - name: Build IPA
        run: ls && xcodebuild -project Unity-iPhone.xcodeproj -scheme Unity-iPhone archive -archivePath ./Unity-iPhone.xcarchive && xcodebuild -exportArchive -archivePath ./Unity-iPhone.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ./app.ipa CODE_SIGNING_ALLOWED=NO
      
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: app.ipa
          path: ./app.ipa
