name: "Build iOS app"

on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBdUdxSWRaOEpvV2NpY29UNGZ2WDBXbG1HdW1rdEE_ZT12dzFpaTc/root/content"
          unzip archive.zip -d .

          xcodebuild archive -project app.xcodeproj -scheme 'app' -archivePath app.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv app.xcarchive/Products/Applications/app.app Payload/app.app

          zip -r "FlappyJam.ipa" "Payload"

          mv FlappyJam.ipa ${{ runner.temp }}/FlappyJam.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: FlappyJam
          path: ${{ runner.temp }}/FlappyJam.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3
